version: '3.8'
services:
  odoo:
    build: .
    container_name: ${CLIENT_NAME}-DEV
    ports:
      - "8069:8069"
      - "8072:8072"
    depends_on:
      - db 
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo/addons:/mnt/addons
      - ./odoo/extra:/mnt/extra
    environment:
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - WDB_SOCKET_SERVER=wdb
      - WDB_WEB_PORT=1984
      - WDB_WEB_SERVER=localhost
    command: --dev all #odoo -u tên module -d database hiện tại
  
  db:
    image: postgres:12
    container_name: ${CLIENT_NAME}-DEV-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:4
    container_name: ${CLIENT_NAME}-DEV-pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    logging:
      driver: "none"

  wdb:
    image: kozea/wdb
    container_name: ${CLIENT_NAME}-DEV-wdb
    ports:
      - "1984:1984"
volumes:
  odoo-data:
  odoo-db:
  pgadmin: